services:
  mysql:
    image: mysql:8.0
    working_dir: /home/db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
      MYSQL_USER: dev
      MYSQL_PASSWORD: secret
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network
    restart: unless-stopped

  proxy:
    image: nginx:stable-alpine
    ports:
      - 8001:80
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/development.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network
    depends_on:
      - server
    restart: unless-stopped

  server:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.server
    ports:
      - 8000:8000
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=app
      - DB_USERNAME=dev
      - DB_PASSWORD=secret
    volumes:
      - ./:/app
    networks:
      - app-network
    depends_on:
      - mysql
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.app
    ports:
      - 5173:5173
    volumes:
      - ./:/var/www/html
    networks:
      - app-network
    depends_on:
      - mysql
    stdin_open: true
    tty: true

  adminer:
    image: adminer:4.8.1
    ports:
      - 8090:8080
    environment:
      - ADMINER_DEFAULT_SERVER=mysql
      - ADMINER_DESIGN=pepa-linha
    networks:
      - app-network
    depends_on:
      - mysql
    restart: unless-stopped

volumes:
  mysql-data:
    driver: local

networks:
  app-network:
    driver: bridge